### ISSUE TITLE
Error Running: Experiments with FedAvg

### ISSUE THREAD

**Issue by IemProg** [debcaldarola/fedsam#5]
Hi, 

wonderful work, and thanks for sharing the code.

Could you please share with us the script to run **the baseline "FedAvg" algorithm** ?

I changed the name of the algorithm from **fedopt** to **fedavg** in the arguments of the script CIFAR10.sh, but i'm getting this error.

```
Running experiment with server servers.fedavg_server and client clients.client
server_path:  servers.fedavg_server
Traceback (most recent call last):
  File "main.py", line 383, in <module>
    main()
  File "main.py", line 71, in main
    Client, Server = get_client_and_server(server_path, client_path)
  File "main.py", line 269, in get_client_and_server
    server_name = list(map(lambda x: x[0], filter(lambda x: 'Server' in x[0] and server_name in x[0].lower(), cls)))[0]
IndexError: list index out of range
```

Thanks !

**Comment by debcaldarola** [comment]
Hi! 
Thanks for pointing this out, I'll update the fixed version of the code as soon as possible.
In the meantime, you can easily run the FedAvg experiment by setting:
- server learning rate: 1
- server optimizer: sgd
- server algorithm: fedopt

That is because applying FedAvg is equivalent to using SGD on the server-side with learning rate 1, and the server-side pseudogradient is the average of the clients' pseudo gradients. 

Hope this helps!
