### ISSUE TITLE
For cifar10 experiment

### ISSUE THREAD

**Issue by ZhengrongZhang** [debcaldarola/fedsam#9]
Dear author
Sorry to bother you. I have a question that when I run the cifar10 experiment it shows:  [Errno 22] Invalid argument: 'results\\cifar10\\cnn\\results_alpha_0.00K5_N10000_clr0.01_fedopt_sgd_slr1.0_120623_16:42:43.txt' Do you know how to fix it?

Best wishes

**Comment by debcaldarola** [comment]
Hi, 
how do you get this error? Which command do you launch?

**Comment by ZhengrongZhang** [comment]
I run the command ./cifar10.sh

**Comment by ZhengrongZhang** [comment]
> Hi, how do you get this error? Which command do you launch?

![error](https://github.com/debcaldarola/fedsam/assets/43168017/52d00473-5f08-4bfc-a3a5-12873b471b5a)
Here is the error

**Comment by debcaldarola** [comment]
I am guessing this is related to Windows being your OS. 
Does the command os.makedirs() create the folders results\cifar10\cnn? Otherwise, have you tried using the path r"results\cifar10\cnn\[..]" rather than using the double backslash? Lastly, you could try to create the file first and then open it with "r" instead of "w".

Let me know if any of this helps!
